version: 2
jobs:
  build:
    
    working_directory: ~/my-app

    docker:
      - image: circleci/openjdk:8-jdk-browsers
        environment:
          SECRET_SAUCE: magic

    steps:

      - checkout

      - restore_cache:
          key: circleci-teststuff-{{ checksum "pom.xml" }}
      
      - run: mvn -f ./my-app/pom.xml install
      
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-teststuff-{{ checksum "pom.xml" }}
      
      # - run: mvn package
      
      - store_test_results:
          path: target/surefire-reports
      
      # - store_artifacts:
      #     path: my-app/target/my-app-1.0-SNAPSHOT.jar
