name: OIDC Tests

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
        
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [push, workflow_dispatch]
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: '<insert name here>'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup jf cli:
    - uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: https://psazuse.jfrog.io
      with:
        oidc-provider-name: chriswhgithub 
        oidc-audience: internal
  
  # This workflow contains a single job called "greet"
  verify:    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
    - run: echo "Hello ${{ inputs.name }}"
    - run: jf rt rpt .
    - run: echo "🎉 The OIDC setup was complete."
