name: Release Bundle forwarding workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Bundle to forward'
        required: true
        default: 'default bundle'
      release_bundle:
        required: false
      bundle_version:
        required: false
      artifact_path:
        description: 'Artifact path'
        required: false
        default: '/'

jobs:
  forward_bundle:
    runs-on: ubuntu-latest
    steps:
    - name: Unpack hook payload
      run: |
        echo "Forwarding bundle: ${{inputs.release_bundle}} version [${{inputs.bundle_version}}] from ${{inputs.name}}"
        echo "Data: ${{inputs.name}}"

    - name: Setup OIDC
      uses: jfrog/setup-jfrog-cli@v4
      env:
        JF_URL: https://psazuse.jfrog.io
      with:
        oidc-provider-name: chriswhgithub 
        oidc-audience: jfrog-github

    - name: Export bundle
      run: jf rbe ${{inputs.release_bundle}} ${{inputs.bundle_version}}

    - name: Extract signing key
      run: echo "Pulling signing keys"

    - name: Import signing keys
      run: echo "Push signing keys to target instance"

    - name: Import bundle to target node
      run: |
        echo "Importing bundle"
        jf rbi ./bundlename.zip

        
      
