name: Release Bundle forwarding workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Bundle to forward'
        required: true
        default: 'default bundle'
      repo:
        description: 'Repo path'
        required: false
        default: '/'
      artifact_path:
        description: 'Artifact path'
        required: false
        default: '/'

jobs:
  forward_bundle:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Forwarding bundle: ${{inputs.repo}} from ${{inputs.artifact_path}}"
        echo "- in $!"
