name: Release Bundle forwarding workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Bundle to forward'
        required: true
        default: 'default bundle'
      release_bundle:
        required: false
      bundle_version:
        required: false
      artifact_path:
        description: 'Artifact path'
        required: false
        default: '/'

jobs:
  forward_bundle:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Forwarding bundle: ${{inputs.release_bundle}} version [${{inputs.bundle_version}}] from ${{inputs.name}}"
        echo "Data: ${{inputs.name}}"
